package se.linusborjesson.scorespeaker.ui

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import se.linusborjesson.scorespeaker.settings.BindableAction

/**
 * Every user-facing UI string, in one language. Provided via [LocalStrings]
 * (Android selects by the language setting; English is the default and the
 * fallback). Pipeline diagnostics on the debug panel (detection method,
 * fps, cache line) stay raw — they're data, not copy.
 *
 * `%d`/`%s` fields are `String.format`-style templates; callers format.
 */
@Immutable
data class Strings(
    // Live screen
    val locked: String,
    val searching: String,
    val historyChip: String,
    val settingsChip: String,
    val backChip: String,
    val backDescription: String,
    val cameraPermissionRequired: String,
    val cameraUnavailable: String,
    val readoutShot: String,
    val readoutScore: String,
    // Settings
    val settingsTitle: String,
    val voiceAndSpeech: String,
    val speechRate: String,
    /** Spoken value for the speech-rate slider; %s = rate like "1.1". */
    val speechRateTimesTemplate: String,
    val language: String,
    val languageSystem: String,
    val languageEnglish: String,
    val languageSwedish: String,
    val announcements: String,
    val scoreAfterEachShot: String,
    val aimOffset: String,
    val aimOffsetSub: String,
    val misses: String,
    val missesSub: String,
    val offsetDecimals: String,
    val offsetDecimalsSub: String,
    val offsetStyle: String,
    val offsetStyleDirections: String,
    val offsetStyleClock: String,
    val verbosity: String,
    val verbosityTerse: String,
    val verbosityNormal: String,
    val keyBindings: String,
    val bindingListeningSub: String,
    val bindingNotBoundSub: String,
    val listeningChip: String,
    val clearChip: String,
    /** %s = action label. */
    val clearBindingForTemplate: String,
    val actionReadLastShot: String,
    val actionReadAvgError: String,
    // Camera group
    val camera: String,
    val cameraZoom: String,
    val cameraZoomSub: String,
    // About group
    val about: String,
    val privacyPolicy: String,
    val privacyPolicySub: String,
    val ossLicenses: String,
    val ossLicensesSub: String,
    // Developer group + debug panel
    val developer: String,
    val debugOverlays: String,
    val debugOverlaysSub: String,
    val autoCaptureShots: String,
    val autoCaptureShotsSub: String,
    // Experimental
    val captureChip: String,
    // History
    val historyTitle: String,
    val lastThirtyDays: String,
    val avgPerShot: String,
    val sessions: String,
    val noSessionsYet: String,
    val bestSessionAvg: String,
    val totalShots: String,
    /** %d = shot count. */
    val shotsCountTemplate: String,
    /** %s = formatted average. */
    val avgTemplate: String,
    /** %d = missed count. */
    val missedTemplate: String,
    /** %d = missed count, %s = comma-joined shot numbers. */
    val missedListTemplate: String,
    /** %d = session index. */
    val sessionTitleTemplate: String,
    /** %d = whole minutes. */
    val minutesTemplate: String,
    // Session detail
    val statTotal: String,
    val statAvg: String,
    val statBest: String,
    val statShots: String,
    val shotGroup: String,
    val shotLog: String,
    val noShots: String,
    // Shot-note words ("Low-right 1.2" / "Centre")
    val noteCentre: String,
    val noteLow: String,
    val noteHigh: String,
    val noteLeft: String,
    val noteRight: String,
) {
    fun actionLabel(action: BindableAction): String = when (action) {
        BindableAction.READ_LAST_SCORE -> actionReadLastShot
        BindableAction.READ_AVG_ERROR_5 -> actionReadAvgError
    }
}

val EnglishStrings = Strings(
    locked = "LOCKED",
    searching = "SEARCHING…",
    historyChip = "HISTORY",
    settingsChip = "SETTINGS",
    backChip = "BACK",
    backDescription = "Back",
    cameraPermissionRequired = "Camera permission required.",
    cameraUnavailable = "This device has no usable rear camera.",
    readoutShot = "Shot",
    readoutScore = "Score",
    settingsTitle = "Settings",
    voiceAndSpeech = "Voice & speech",
    speechRate = "Speech rate",
    speechRateTimesTemplate = "%s times",
    language = "Language",
    languageSystem = "System",
    languageEnglish = "English",
    languageSwedish = "Swedish",
    announcements = "Announcements",
    scoreAfterEachShot = "Score after each shot",
    aimOffset = "Aim offset",
    aimOffsetSub = "\"left 3, down 1\" after each shot",
    misses = "Off-target shots",
    missesSub = "\"shot 16, miss, 8 o'clock\" — otherwise silent",
    offsetDecimals = "Error decimals",
    offsetDecimalsSub = "\"left 3.1\" instead of \"left 3\"",
    offsetStyle = "Error style",
    offsetStyleDirections = "Directions",
    offsetStyleClock = "Clock",
    verbosity = "Verbosity",
    verbosityTerse = "Terse",
    verbosityNormal = "Normal",
    keyBindings = "Key bindings",
    bindingListeningSub = "Press a key… (tap again to cancel)",
    bindingNotBoundSub = "Not bound — tap, then press a key",
    listeningChip = "LISTENING…",
    clearChip = "CLEAR",
    clearBindingForTemplate = "Clear binding for %s",
    actionReadLastShot = "Read last shot (score and error)",
    actionReadAvgError = "Read average error (last 5 shots)",
    camera = "Camera",
    cameraZoom = "Zoom",
    cameraZoomSub = "Fill the frame with the display. Higher values use the telephoto lens where available.",
    about = "About",
    privacyPolicy = "Privacy policy",
    privacyPolicySub = "Opens the policy in your browser.",
    ossLicenses = "Open source licenses",
    ossLicensesSub = "Third-party software this app is built on.",
    developer = "Developer",
    debugOverlays = "Debug overlays",
    debugOverlaysSub = "Detection HUD + the cell crops OCR reads, live",
    autoCaptureShots = "Auto-capture new shots",
    autoCaptureShotsSub = "One annotated capture (~2 MB) per detected shot — turns itself off under 1 GB free",
    captureChip = "CAPTURE",
    historyTitle = "History",
    lastThirtyDays = "Last 30 days",
    avgPerShot = "avg / shot",
    sessions = "Sessions",
    noSessionsYet = "No sessions yet.\nShots are recorded automatically as you shoot.",
    bestSessionAvg = "Best session avg",
    totalShots = "Total shots",
    shotsCountTemplate = "%d shots",
    avgTemplate = "avg %s",
    missedTemplate = "%d missed",
    missedListTemplate = "%d missed (%s)",
    sessionTitleTemplate = "Session %d",
    minutesTemplate = "%d min",
    statTotal = "Total",
    statAvg = "Avg",
    statBest = "Best",
    statShots = "Shots",
    shotGroup = "Shot group",
    shotLog = "Shot log",
    noShots = "No shots",
    noteCentre = "Centre",
    noteLow = "low",
    noteHigh = "high",
    noteLeft = "left",
    noteRight = "right",
)

val SwedishStrings = Strings(
    locked = "LÅST",
    searching = "SÖKER…",
    historyChip = "HISTORIK",
    settingsChip = "INSTÄLLNINGAR",
    backChip = "TILLBAKA",
    backDescription = "Tillbaka",
    cameraPermissionRequired = "Kameratillstånd krävs.",
    cameraUnavailable = "Enheten saknar en användbar bakre kamera.",
    readoutShot = "Skott",
    readoutScore = "Poäng",
    settingsTitle = "Inställningar",
    voiceAndSpeech = "Röst & tal",
    speechRate = "Talhastighet",
    speechRateTimesTemplate = "%s gånger",
    language = "Språk",
    languageSystem = "System",
    languageEnglish = "Engelska",
    languageSwedish = "Svenska",
    announcements = "Uppläsning",
    scoreAfterEachShot = "Poäng efter varje skott",
    aimOffset = "Träffavvikelse",
    aimOffsetSub = "\"vänster 3, ner 1\" efter varje skott",
    misses = "Bomskott",
    missesSub = "\"skott 16, bom, klockan 8\" — annars tyst",
    offsetDecimals = "Decimaler i avvikelsen",
    offsetDecimalsSub = "\"vänster 3,1\" istället för \"vänster 3\"",
    offsetStyle = "Avvikelseformat",
    offsetStyleDirections = "Riktningar",
    offsetStyleClock = "Klockan",
    verbosity = "Detaljnivå",
    verbosityTerse = "Kortfattad",
    verbosityNormal = "Normal",
    keyBindings = "Tangentbindningar",
    bindingListeningSub = "Tryck på en tangent… (tryck igen för att avbryta)",
    bindingNotBoundSub = "Ej bunden — tryck här, sedan på en tangent",
    listeningChip = "LYSSNAR…",
    clearChip = "RENSA",
    clearBindingForTemplate = "Rensa bindning för %s",
    actionReadLastShot = "Läs upp senaste skottet (poäng och avvikelse)",
    actionReadAvgError = "Läs upp snittfel (senaste 5 skotten)",
    camera = "Kamera",
    cameraZoom = "Zoom",
    cameraZoomSub = "Fyll bilden med tavlan. Högre värden använder telelinsen om den finns.",
    about = "Om",
    privacyPolicy = "Integritetspolicy",
    privacyPolicySub = "Öppnar policyn i din webbläsare.",
    ossLicenses = "Öppen källkod-licenser",
    ossLicensesSub = "Tredjepartsprogramvara som appen bygger på.",
    developer = "Utvecklare",
    debugOverlays = "Felsökningsvyer",
    debugOverlaysSub = "Detekterings-HUD + cellbilderna som OCR läser, live",
    autoCaptureShots = "Fånga nya skott automatiskt",
    autoCaptureShotsSub = "En annoterad bild (~2 MB) per upptäckt skott — stänger av sig själv under 1 GB ledigt",
    captureChip = "FÅNGA",
    historyTitle = "Historik",
    lastThirtyDays = "Senaste 30 dagarna",
    avgPerShot = "snitt / skott",
    sessions = "Pass",
    noSessionsYet = "Inga pass än.\nSkott registreras automatiskt när du skjuter.",
    bestSessionAvg = "Bästa passets snitt",
    totalShots = "Antal skott",
    shotsCountTemplate = "%d skott",
    avgTemplate = "snitt %s",
    missedTemplate = "%d missade",
    missedListTemplate = "%d missade (%s)",
    sessionTitleTemplate = "Pass %d",
    minutesTemplate = "%d min",
    statTotal = "Totalt",
    statAvg = "Snitt",
    statBest = "Bästa",
    statShots = "Skott",
    shotGroup = "Träffbild",
    shotLog = "Skottlogg",
    noShots = "Inga skott",
    noteCentre = "Centrerat",
    noteLow = "låg",
    noteHigh = "hög",
    noteLeft = "vänster",
    noteRight = "höger",
)

/** UI strings for a BCP-47 language code: Swedish for "sv", else English. */
fun uiStrings(language: String): Strings =
    if (language == "sv") SwedishStrings else EnglishStrings

val LocalStrings = staticCompositionLocalOf { EnglishStrings }
